### PR TITLE
Confirm dialog keyboard support

### PR DESCRIPTION
**Pull request by andreptb**
Hi @mattlewis92,

Great work on this plugin! However, I couldn't find a way to use the keyboard to press the buttons on the dialog in an easy way. I want to press enter on a button and when the confirm dialog shows up, I want to press enter again to confirm it. 

In this pull request I make this work by applying focus to the first button after the popup is shown. To cancel you can go to the next button by pressing tab and then press enter.

### CODE REVIEW

**Comment by mattlewis92** [comment]
Hi thanks for this, it looks great! There are a few small improvements that need making before this can be merged if that's OK.

- [ ] The unit tests are failing
- [ ] Can you add additional tests for the functionality you added
- [ ] Could you make this an option that you can toggle on / off (and set a global default as well)

**Comment by andreptb** [comment]
@mattlewis92,

Created a new commit with the following:

- All unit tests are [passing](https://travis-ci.org/mattlewis92/angular-bootstrap-confirm/builds/82452865).
- Additional tests, had a hard time to make it work with [phantomjs limitations](https://github.com/ariya/phantomjs/issues/10427).
- **handle-focus** option to allow toggling this functionality. It's enabled by default, I believe confirming with the keyboard is a very desirable feature.

**Comment by mattlewis92** [comment]
Thanks fantastic, thanks for making those changes! I've released 0.4.0 now which includes your additions :smile:

**Comment by andreptb** [comment]
No problem! Thanks for the fast release!

**Pull request merged**
