### PR TITLE
Added ability to override the template

### PR DESCRIPTION
**Pull request by scottjbos**
Added ability to override template and auto focus the confirmation button by default.

### CODE REVIEW

**Comment by mattlewis92** [comment]
This is great thanks!

Couple of small tweaks:
-can you remove the dist files and version bump from the PR as I'll do that on the next release
-can you add a test for the custom template 

After making the changes can you squash them together into a single commit

**Comment by scottjbos** [comment]
Do you have a suggestion on how to include the a .run() block in a test somehow to override the template?  I'm struggling with getting that to work.

**Comment by mattlewis92** [comment]
You don't need to include the run block in the test:
```
it('should override the popover template', inject(function(confirmationPopoverDefaults) {
  confirmationPopoverDefaults.template = templateHtml;
  // do the test here...
}));
```

:smile:

**Comment by scottjbos** [comment]
Thanks for you help Matt!  I added 2 extra tests to verify the template code works.  I don't know how to squish all my commits into one, like you mentioned before, so I think that is the last hurdle.

**Comment by mattlewis92** [comment]
Awesome, thanks! This should help you squash the commits: http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

**Comment by scottjbos** [comment]
So the 7th commit seems to contain all of my changes in one commit, but now it shows as 8 commits.  I could cherry pick that commit into a new branch and close this pull request and open a new one.  But I am not sure how else to make everything show up as one commit.

**Comment by scottjbos** [comment]
Closing this pull request in favor of PR #13 which has all of my changes in just one commit.

**Pull request closed without merging**
