### PR TITLE
Added ability to override the template

### PR DESCRIPTION
**Pull request by scottjbos**
Added the ability to override the pop over template html and a test verifying the default template and a test verifying a overriden template.

### CODE REVIEW

**Comment by mattlewis92** [comment]
LGTM, thanks!

**Comment by scottjbos** [comment]
Great!  Do you have an idea of when we can expect 0.5.3 to be released?

**Comment by mattlewis92** [comment]
I'm away at a conference at the moment and the internet here is terrible, so will cut a new release when I get back home tomorrow

**Comment by mattlewis92** [comment]
0.6.0 is now released, I tweaked your code a bit so you now use a `templateUrl` property rather than a template so you don't have to inline your template :smile:

**Pull request merged**
